---
title: "p8105_hw3_zc2610"
author: "Zuoqiao Cui"
date: "2022-10-07"
output: github_document
---
```{r}
library(tidyverse)
```
## Problem 2
Import data
```{r}
acc_df = read.csv("./data/accel_data.csv") %>% 
  janitor::clean_names()
```
combine all activity columns
```{r}
acc_df = acc_df %>% 
  pivot_longer(
    activity_1:activity_1440,
    names_to = "activity",
    values_to = "counts/minute",
    names_prefix = "activity_"
  )
```
create a weekday vs weekend variable
```{r}
acc_df = acc_df %>% 
  mutate(
    weekday_or_weekend = case_when(
      day == "Monday" ~ "weekday",
      day == "Tuesday" ~ "weekday",
      day == "Wednesday" ~ "weekday",
      day == "Thursday" ~ "weekday",
      day == "Friday" ~ "weekday",
      day == "Saturday" ~ "weekend",
      day == "Sunday" ~ "weekend",
      TRUE     ~ ""
    ) 
  )
```

```{r}
colnames(acc_df)
nrow(acc_df)
ncol(acc_df)
```

Description

1. The resulting dataset contains following variables: `r colnames(acc_df)`

2. There are totally `r nrow(acc_df)` observations and `r ncol(acc_df)` variables in the resulting dataset







